### ISSUE TITLE
No way to write a package-config to string/buffer without IO

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/package_config#100]
See comment around: (https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/dart/pub.dart#L470)

This functionality exists in src/ but is not exposed in the public interface.

**Comment by jonasfj** [comment]
I think you just:
 * use [`PackageConfig.writeString`](https://pub.dev/documentation/package_config/latest/package_config.package_config_discovery/PackageConfig/writeString.html)
 *  with [`StringBuffer`](https://api.dart.dev/beta/2.12.0-133.2.beta/dart-core/StringBuffer-class.html) from `dart:core`.

**Example** :tada: 
```dart
final buf = StringBuffer();
PackageConfig.writeString(packageConfig, buf);
final serializedPackageConfig = buf.toString();
```

There could be a convenient method for it..

------

@sigurdm, Am I missing something, or is that what you want to do?

**Comment by sigurdm** [comment]
Indeed - I missed that one! I did not expect it to be a static function on PackageConfig.

It indeed solves this problem!

This also solves (most of): https://github.com/dart-lang/package_config/issues/99 .

Here you can chose to not pass a base-uri. And then you would get absolute uris for those that are already relative.
