### ISSUE TITLE
API for collecting all "context root" subdirectories from a given directory 

### ISSUE THREAD

**Issue by pq** [dart-lang/package_config#19]
For `analyzer` (and `server`) integration we need a means to map a directory to it's subdirectories which have corresponding package maps (and so should be treated as analysis context roots).

Not a good name but this captures the basic idea.
```
/// Given this directory find all subdirectories for which there is a new
/// package map.
static Future<Map<Directory,Packages>> findAll(Directory dir);
```

**Comment by sethladd** [comment]
If a subdirectory doesn't have a .packages, but does have a packages/ dir, does that count as a "context root" ?

**Comment by lrhn** [comment]
I think you could probably use a packages directory as the default package configuration for all sub-dirs (it should be the default for the packages directory at least) if there is nothing else specifying the package resolution for the subdirs.

This is for the analyzer which has to analyze files that are not scripts/entry-points as well. That means that it has to do some guessing to figure out which entry-point a file belongs to and then use the package configuration of that entry point. 
Using a packages dir in a parent directory is one heuristic that can be used. You can always update it later if you get more information by looking at the import structures.

**Comment by lrhn** [comment]
Would it be sufficient to be able to get a Pacakges object for any sub-dir? Or do you need to know the context roots explicitly?

**Comment by lrhn** [comment]
Code landed. If it doesn't work out, please file new bugs against that.
