### ISSUE TITLE
Migrate to `Uri.normalizePath()` and `Iterable.empty`.

### ISSUE THREAD

**Issue by pq** [dart-lang/package_config#2]
We could cleanup `packagemap.dart` and get away from defining our own stand-in:

`
static Uri _normalizePath(Uri existingUri) => new Uri().resolveUri(existingUri);
`

and migrate to using `Uri.normalizePath()`.

If we do this, we'll need to up our SDK contsraint to be `>=1.11`.

**Comment by sethladd** [comment]
Go for it! packages.cfg won't have initial support until at least 1.11

**Comment by pq** [comment]
This is breaking observatory.  Rolling back.

cc @hterkelsen

**Comment by hterkelsen** [comment]
I think that the Uri.directory constructor also has to go. It's not in 1.10 https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Uri

**Comment by lrhn** [comment]
And we also rolled back the Iterable.empty use, which should also go back with 1.11.

**Comment by pq** [comment]
> And we also rolled back the Iterable.empty use, which should also go back with 1.11.

3175bb9f34eb38d149cf98e9c1d82a901881e6e0

**Comment by pq** [comment]
Wow this has languished!

Fix up here: #46.
