### ISSUE TITLE
Add dartfmt to Travis build, and fail if unformatted

### ISSUE THREAD

**Issue by sethladd** [dart-lang/package_config#22]

**Comment by sethladd** [comment]
We use https://github.com/dart-lang/dartdoc/blob/master/tool/ensure_dartfmt.sh in dartdoc.

Wired into this script: https://github.com/dart-lang/dartdoc/blob/master/tool/travis.sh

**Comment by lrhn** [comment]
We do *not* require that files are formatted with Dart-format.
