### ISSUE TITLE
add support for qualified package names

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/package_config#23]
This is to support imports like `package:foo.bar.baz/src/quox.dart`.

**Comment by sigmundch** [comment]
https://codereview.chromium.org/1176153002/

**Comment by lrhn** [comment]
I don't think Pub allows package names that are not identifiers (at least that's what I think I have been told).

The file format is specified to only allow identifiers, if we change that we need buy-in from the people implementing it (mostly the VM).

The package:-URIs are not specified anywhere, so it's not clear which characters are allowed (it's not any pchar).

**Comment by sigmundch** [comment]
This is no longer needed, as the new proposed changes to the DEP will cover our use case. We can use #24 to track the implementation of that.
