### ISSUE TITLE
Clarify changelog entry

### ISSUE THREAD

**Issue by nex3** [dart-lang/package_config#27]
Currently the changelog entry for version 1.1 just says "syntax updates", with no more context. This doesn't provide a user with useful information about what version to depend on. Please include more information: what part of the syntax was updated? In what ways is it still backwards-compatible? Can you link to a spec update the user can look at for more information?

**Comment by lrhn** [comment]
The 1.1 syntax updates have been dropped again, so we won't be documenting that, only deprecating it, and releasing a 2.0 instead.

**Comment by lrhn** [comment]
We are back at the specification for version 2 not having a final location yet. When they exist, we will link to them.

**Comment by lrhn** [comment]
The current README.md links to the current format specification.
