### ISSUE TITLE
No apparent way to get the literal URI from the original .packages file

### ISSUE THREAD

**Issue by sethladd** [dart-lang/package_config#34]
Consider an entry like:

`foo:../bar/lib`

If I parse that with `parse()`, the URI I get back is a full `file://` URI.

I can't seem to find a way to get the literal and original URI from the .packages file, after parsing.

Any thoughts?  Thanks!

**Comment by sethladd** [comment]
This means, among other things, that if I do this: `write(parse(contentsOfDotPackages))` the output will not match the input. That may be OK, for example the ordering probably doesn't matter. But the URIs, though probably equivalent, will be different.

**Comment by lrhn** [comment]
A relative URI reference like this is resolved relative to the `.packages` file. The literal URI reference is useless on its own, giving it to you will at best be useless, and at worst it's error prone.
If you want to write the file with relative paths, use the `baseUri` parameter on `write` to specify which location the URIs should be relative to.

So, no plan to change this.
