### ISSUE TITLE
.packages file fails to parse if it ends in a blank line

### ISSUE THREAD

**Issue by johnmccutchan** [dart-lang/package_config#35]
'''test_package:lib/''' parses

but:

'''test_package:lib/
'''

results in the error:

FormatException: No ':' on line (at offset 16)

Because the analyzer doesn't surface these errors I just wasted hours tracking this down.

**Comment by johnmccutchan** [comment]
@sethladd @pq

**Comment by pq** [comment]
Oh.  That sucks.  (The problem with errors getting buried is another axe.)

@johnmccutchan : I'm guessing the fix you're proposing here is to make the parser OK with blank lines?

We should consider opening a corresponding bug on the analyzer to address your beef with error reporting.

**Comment by johnmccutchan** [comment]
My request for this package: make the parser ignore blank lines

My request for analyzer / analysis_server: Have a clear way for us to surface important info to the developer in Atom. For example: Your .packages can't be parsed or package foo's _embedder.yaml is busted.

**Comment by pq** [comment]
Awesome.  

> My request for analyzer / analysis_server: Have a clear way for us to surface important info to the developer in Atom. For example: Your .packages can't be parsed or package foo's _embedder.yaml is busted.

Would you mind opening that bug?  Feel free to assign to me.

**Comment by pq** [comment]
> Would you mind opening that bug? Feel free to assign to me.

Actually, done: https://github.com/dart-lang/sdk/issues/24889

**Comment by pq** [comment]
Ok, so I wasn't able to reproduce this.  Any chance you hadn't run a `pub update` (or were not using the version of `package_config` currently in `DEPS`) and had a stale library?

**Comment by johnmccutchan** [comment]
Let's assume this is stale.
