### ISSUE TITLE
[1.9] Consider static methods on `PackageConfig` instead of top level methods

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#63]
Static methods like `PackageConfig.find`, `PackageConfig.load` would be more discoverable than the top level ones.

**Comment by jakemac53** [comment]
@lrhn

**Comment by lrhn** [comment]
That's another approach. I tend to prefer top-level functions for things that are the main functionality of the library (the `PackageConfig` is just one of the classes it produces, it's data, not the main operation).

I have no issues with top-level functions as an API, and I don't necessarily start my API search at classes, but it is true that some people do.

I certainly can do that (it would be yet another API change, which means I'd have to fix the front end, but that's doable).

Anyone have opinions?

**Comment by lrhn** [comment]
Doing that would also prevent #62, because the `load` method depends on `dart:io` and putting it on the main `PackageConfig` class makes separation impossible.

**Comment by jakemac53** [comment]
I do think it would be a bit weird to have the `dart:io` versions be different so I am fine with keeping the current approach. The main reason I like the static methods is because of discoverability - you can type `PackageConfig.` in your IDE and see everything available but with top level methods you get no such help, you have to go read the docs for the package. Not a big deal though.

If we had could add static methods with extensions I would say do that but we don't so its probably best to be consistent with the top level methods :man_shrugging: .

**Comment by lrhn** [comment]
There is now a package_config_types.dart library with no dart:io dependency. Kept the top-level functions in package_config.dart
