### ISSUE TITLE
[1.9] Add a way to create a PackageConfig synchronously

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#64]
Related to https://github.com/dart-lang/package_config/issues/62 (and would likely be solved by solving that).

Assuming you have a package config file already loaded in memory you should be able to synchronously parse and load that config into a `PackageConfig` instance.

**Comment by jakemac53** [comment]
@lrn

**Comment by lrhn** [comment]
That suggests a `parseBytes` method on `PackageConfig`.
We can do that.

**Comment by lrhn** [comment]
Done. It's on 1.9-allow-overlap.
