### ISSUE TITLE
Release as 1.2 (instead of 1.9?)

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/package_config#70]
1.2 is already in the changelog – but never shipped! (we should fix that either way)

Any reason to jump to 1.9?

CC @jakemac53

**Comment by kevmoo** [comment]
Also consider this the request to publish 😄

**Comment by lrhn** [comment]
The 1.9 version was picked to look "final". This is not a simple progression of the API, it is the final version of 1.x, before the old API is removed in 2.0.

Will fix changelog and publish 1.9.

**Comment by kevmoo** [comment]
package_config 1.9.1 is out!
