### ISSUE TITLE
Widespread test failures with version 1.9

### ISSUE THREAD

**Issue by aaronlademann-wf** [dart-lang/package_config#72]
Hi there @kevmoo @lrhn,

We are seeing widespread failures across all of our Dart CI builds at Workiva as a result of the `1.9.0` release of this package.

Failures are of the form:

```
Failed to load "<path_to_a_test_entrypoint>.dart": Failed to load script at 
http://localhost:43031/DT4tNLNNdu4ivzkLd5RQn9vcGbvHr%2FRe/<path_to_a_test_entrypoint>.dart.browser_test.dart.js.
```

**Comment by kevmoo** [comment]
@jakemac53

**Comment by kevmoo** [comment]
@aaronlademann-wf  Running browser tests with pkg:test? Using pkg:build_test?

**Comment by jakemac53** [comment]
It sounds like we aren't compiling the apps at all - are you seeing warning logs about us skipping compiling an entrypoint due to it having an unsupported import somewhere?

**Comment by todbachman-wf** [comment]
Yep, such as:

```
2020-02-26T20:19:47.461048102Z Skipping compiling wdesk_sdk|test/unit/browser/truss_4/generated_runner_test.dart.browser_test.dart with ddc because some of its
2020-02-26T20:19:47.461051967Z transitive libraries have sdk dependencies that not supported on this platform:
2020-02-26T20:19:47.461055397Z 
2020-02-26T20:19:47.461058381Z package_config|lib/src/util.dart
```

**Comment by aaronlademann-wf** [comment]
@jakemac53 yes. Here is an OSS build/test failure: https://travis-ci.org/Workiva/over_react/jobs/655532414?utm_medium=notification&utm_source=github_status

**Comment by jakemac53** [comment]
Looks like a `dart:io` import was added to that utils file - as far as I can tell its only actually imported [here](https://github.com/dart-lang/package_config/blob/master/lib/src/packages_impl.dart#L14) which is only using the `checkValidPackageUri`  method so we could move that out to a different file or move the things that need `dart:io` to a different file.

**Comment by aaronlademann-wf** [comment]
Thanks for the quick turnaround on this @jakemac53 !!!
