### ISSUE TITLE
savePackageConfig throws if `.dart_tool` dir doesn't already exist

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#86]
This package should make sure to use `recursive: true` when creating files.

This primarily causes problems in tests, typical use cases already would have a `.dart_tool` dir from a pub get/upgrade.

**Comment by lrhn** [comment]
It should not throw, the documentation states that the directory should be created.

It should not need to be *recursive* if it assumes that the target directory must exist. This is not documented, though.

**Comment by jakemac53** [comment]
Note that the target directory _does_ exist, but the file is written to `.dart_tool/package_config.json`, so it throws if the `.dart_tool` dir doesn't exist in the target dir, which is surprising.

I think it would be fine to assume `targetDir` does exist, but not the `.dart_tool` dir under that.

**Comment by lrhn** [comment]
Have added code to create directory recursively when saving.
