### ISSUE TITLE
The default package version should be the current version, but it is 2.7

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/package_config#90]
The behavior I expected is that all packages in the allow list would be opted in in this case, since they get the latest language version.

This behavior is not however fully specified, and making this change today would be very breaking. Primarily this is a question of _how_ exactly things break when only a regular `.packages` file is present. Either some packages in the allow list that are not actually migrated yet would be opted in when they shouldn't be, or migrated versions will not be opted in (the current behavior).

An example repro is to check out the [collection](https://github.com/dart-lang/collection) package, and add this file at `lib/test.dart`:

```dart
main() {
  int? x;
  print(x);
}
```

If you run that with `dart lib/test.dart` it works fine.

If you then add an empty `.packages` file at `lib/.packages` and re-run, it will fail saying the package is not opted in.

**Comment by lrhn** [comment]
The behavior is deliberate. We can argue whether it's the right one.

If you have a `.packages` file, but not `package_config.json` file, you are stuck at the language version before language versioning was introduced. You can't go above that without actually specifying a language version, and you can't specify a language version with a `.packages` file.
A `.packages` file is not ` package_config.json` file without a `languageVersion` entry, it's a configuration ignorant of the existence of language versioning entirely. That means that it's a Dart 2.7 configuration.
From Dart 2.8 and forward, the Dart language is versioned, and you need `package_config.json` file to use it.

Forcing a `.packages` file to keep you at the 2.7 language is strict. It's intended to *force* a migration to `package_config.json`. 

(The complete absence of any configuration file is taken as using the most current language version. It also precludes using any packages, so you can only be incompatible with yourself, and that's your own problem).

**Comment by jakemac53** [comment]
> The "if there is no `package_config.json` file" does not cover using a `.packages` file.

I don't see how this doesn't cover the case we are talking about - there is no package_config.json file when only a `.packages` file is provided. If we wanted a `.packages` file to have some special meaning that should be explicitly specified there, it doesn't leave any ambiguity as is.

That being said, I don't think we necessarily need to change the behavior this at this point, and I do think that `2.7` is a reasonable default, regardless of how you interpret the spec.

**Comment by jakemac53** [comment]
I am going to close this as not planned
