### ISSUE TITLE
publish null-safe `package_config`

### ISSUE THREAD

**Issue by pq** [dart-lang/package_config#97]
Once #96 lands, are we good to publish?

What do you think @lrhn?

**Comment by pq** [comment]
Is this ready to be pulled into the SDK or are there analyzer issues?

**Comment by pq** [comment]
See also https://github.com/dart-lang/package_config/pull/93#issuecomment-742120958

**Comment by jakemac53** [comment]
@lrhn it looks like a version was published but with `-dev` as the pre-release, we are using `-nullsafety` as the pre-release versions as an ecosystem wide convention ([see public guidance here](https://dart.dev/null-safety/migration-guide#version)). Can you re-publish with that convention?

**Comment by devoncarew** [comment]
pinging this issue as when running `pub outdated`, a casual read of the output makes it look like package_config does not yet have a null safe version:

the outdated for package:analyzer:

```
direct dependencies:   
args                    *1.6.0     *1.6.0      *1.6.0      2.0.0-nullsafety.0    
cli_util                *0.2.0     *0.2.0      *0.2.0      0.3.0-nullsafety.0    
convert                 *2.1.1     *2.1.1      *2.1.1      3.0.0-nullsafety.0    
crypto                  *2.1.5     *2.1.5      *2.1.5      3.0.0-nullsafety.0    
glob                    *1.2.0     *1.2.0      *1.2.0      2.0.0-nullsafety.0    
meta                    *1.2.4     *1.2.4      *1.2.4      1.3.0-nullsafety.6    
package_config          *1.9.3     *1.9.3      *1.9.3      2.0.0-dev             
path                    *1.7.0     *1.7.0      *1.7.0      1.8.0-nullsafety.3    
pub_semver              *1.4.4     *1.4.4      *1.4.4      2.0.0-nullsafety.0    
source_span             *1.7.0     *1.7.0      *1.7.0      1.8.0-nullsafety.4    
watcher                 *0.9.7+15  *0.9.7+15   *0.9.7+15   1.0.0-nullsafety.0 
```

**Comment by lrhn** [comment]
I have uploaded a pubspec with version 2.0.0-nullsafety.0 and published it.

**Comment by devoncarew** [comment]
Thanks!

**Comment by scheglov** [comment]
Are we ready to pull it into SDK?
IIRC last time when I tried there were some issues with `pub`.
Totally might have been fixed, or plainly disremembered.

**Comment by scheglov** [comment]
I landed https://dart-review.googlesource.com/c/sdk/+/180242.
